name: Generate rules

on:
  push:
    branches: [ master ]
    paths:
    - 'accelerated-domains.china.conf'

jobs:
  deploy:
    name: Generate rules for Dnsmasq/SwitchyOmega/Clash
    runs-on: ubuntu-latest
    env:
      AccessToken: ${{secrets.COMMIT_SECRET}}
      DeployKey: ${{secrets.ACTIONS_DEPLOY_KEY}}

    steps:
    - uses: actions/checkout@v2

    - name: Setup sshkey
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        echo "$DeployKey" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Init repo
      shell: bash
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "actions-user@users.noreply.github.com"
        #git remote set-url origin https://$AccessToken@github.com/$GITHUB_REPOSITORY.git
        git remote set-url origin git@github.com:$GITHUB_REPOSITORY.git

    - name: Commit and push files
      shell: bash
      env:
        Branch: list
        Origin: accelerated-domains.china.conf
        Clash: accelerated-domains.china.yml
        SwitchyOmega: accelerated-domains.china.sorl
      run: |
        git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin $Branch
        git checkout --force -B $Branch refs/remotes/origin/$Branch
        git checkout master -- $Origin
        chmod +x ./gen.sh
        sh ./gen.sh
        git add $Origin $Clash $SwitchyOmega
        git commit -m "$(date +%F)"
        git push origin $Branch
